### ISSUE TITLE
Adapter breaks iobroker Windows installation

### ISSUE THREAD

**Issue by mpfeiler** [AlCalzone/ioBroker.tradfri#398]
When the tradfri adapter is installed on an iobroker installation that is setup using the Windows installation package following errors appear in the log and the iobroker instance stops working:

```
	info	Restart adapter system.adapter.tradfri.0 because enabled
	error	instance system.adapter.tradfri.0 terminated with code 7 (ADAPTER_ALREADY_RUNNING)
	error	Caught by controller[1]: at process._fatalException (internal/bootstrap/node.js:497:27)
	error	Caught by controller[1]: at process.emit (events.js:198:13)
	error	Caught by controller[1]: at process.onUnhandledError (C:\Program Files\iobroker\TG24QA\node_modules\iobroker.tradfri\build\main.js:752:13)
	error	Caught by controller[1]: TypeError: Cannot read property 'log' of undefined
	error	Caught by controller[1]:
	error	Caught by controller[1]: ^
	error	Caught by controller[1]: adapter.log.error("unhandled exception:" + getMessage(err));
	error	Caught by controller[1]: \main.js:752
	error	Caught by controller[0]: C:\Program Files\iobroker\TG24QA\node_modules\iobroker.tradfri\build
	info	instance system.adapter.tradfri.0 started with pid 6816
	info	"system.adapter.tradfri.0" enabled
```

This is reproducible all the time also on a fresh installed instance with no other (non default) adapters. Uninstall does not solve the issue, following error is displayed in that case:

```
Error: Cannot find module 'core-util-is'
--
  | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
  | at Function.Module._load (internal/modules/cjs/loader.js:562:25)
  | at Module.require (internal/modules/cjs/loader.js:692:17)
  | at require (internal/modules/cjs/helpers.js:25:18)
  | at Object.<anonymous> (C:\Program Files\iobroker\TG24QA\node_modules\verror\lib\verror.js:9:19)
  | at Module._compile (internal/modules/cjs/loader.js:778:30)
  | at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
  | at Module.load (internal/modules/cjs/loader.js:653:32)
  | at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
  | at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by AlCalzone** [comment]
Seems unlikely that this adapter is the root issue, since it does nothing special.
@Stabilostick any idea if this has to do with the Windows installer?

**Comment by Stabilostick** [comment]
> @Stabilostick any idea if this has to do with the Windows installer?

Yes. Seen this several times. npm starts suddenly to uninstall modules during installation of ioBroker.tradfri.

**Comment by AlCalzone** [comment]
Do you know why? Is this something that might be fixed with the new installer?

**Comment by Stabilostick** [comment]
Must be something with npm & package-lock or cache. New installer is going to address this.

**Comment by AlCalzone** [comment]
Closing, since this is a general issue with the Windows installation
