### ISSUE TITLE
Reduce logging of "updated scenes for group..."

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/ioBroker.tradfri#45]

**Comment by AlCalzone** [comment]
This is the stack trace when it happens:


tradfri.0 | 2018-05-05 15:28:24.522 | info | at TradfriClient.observeScene_callback (/opt/iobroker/node_modules/node-tradfri-client/build/tradfri-client.js:566:14)
-- | -- | -- | --
tradfri.0 | 2018-05-05 15:28:24.522 | info | at TradfriClient.emit (events.js:213:7)
tradfri.0 | 2018-05-05 15:28:24.522 | info | at emitTwo (events.js:125:13)
tradfri.0 | 2018-05-05 15:28:24.522 | info | at TradfriClient.tradfri_sceneUpdated (/opt/iobroker/node_modules/iobroker.tradfri/build/main.js:521:28)
tradfri.0 | 2018-05-05 15:28:24.522 | info | at Object.updatePossibleScenes (/opt/iobroker/node_modules/iobroker.tradfri/build/lib/iobroker-objects.js:189:12)
tradfri.0 | 2018-05-05 15:28:24.522 | info | at __awaiter (/opt/iobroker/node_modules/iobroker.tradfri/build/lib/iobroker-objects.js:3:12)
tradfri.0 | 2018-05-05 15:28:24.522 | info | at new Promise (<anonymous>)
tradfri.0 | 2018-05-05 15:28:24.522 | info | at /opt/iobroker/node_modules/iobroker.tradfri/build/lib/iobroker-objects.js:7:71
tradfri.0 | 2018-05-05 15:28:24.522 | info | at Generator.next (<anonymous>)
tradfri.0 | 2018-05-05 15:28:24.522 | info | at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.tradfri/build/lib/iobroker-objects.js:201:50)
tradfri.0 | 2018-05-05 15:28:24.522 | info | invoked from: Error
tradfri.0 | 2018-05-05 15:28:24.522 | info | updating possible scenes for group 131073: ["196608","196609","196610","196612"]
