### ISSUE TITLE
Problem with decimal places

### ISSUE THREAD

**Issue by gaudes** [AlCalzone/ioBroker.tradfri#62]
Hi,

I'm using Tradfri Adapter in version 1.4.1.

I've configured the decimal places in the adapter settings to 0.

This is working for single light bulbs. But when I use Tradfri's own groups or virtual groups of the adapter I always get decimal places.

Any ideas ?

Thanks and regards,

Ralf

**Comment by AlCalzone** [comment]
That might be an oversight on my part. Thanks for the report, I'll check it out.

**Comment by AlCalzone** [comment]
Please try v1.5.3 which I just released.

**Comment by gaudes** [comment]
Hi,

sorry, but I get a bunch of errors when trying to upgrade:

```install https://github.com/AlCalzone/ioBroker.tradfri/tarball/master
npm install https://github.com/AlCalzone/ioBroker.tradfri/tarball/master --production --save --prefix "/opt/iobroker" (System call)
npm ERR! path /root/.npm/_logs
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall scandir
npm ERR! Error: EACCES: permission denied, scandir '/root/.npm/_logs'
npm ERR!  { Error: EACCES: permission denied, scandir '/root/.npm/_logs'
npm ERR!   stack: 'Error: EACCES: permission denied, scandir \'/root/.npm/_logs\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'scandir',
npm ERR!   path: '/root/.npm/_logs' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).
glob error { Error: EACCES: permission denied, scandir '/root/.npm/_logs'
  stack: 'Error: EACCES: permission denied, scandir \'/root/.npm/_logs\'',
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs' }
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for node-aead-crypto@2.0.0 and node@8.12.0 (node-v57 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/opt/iobroker/node_modules/node-aead-crypto/build'
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/8.12.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/opt/iobroker/node_modules/node-aead-crypto/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/opt/iobroker/node_modules/node-aead-crypto/.node-gyp'
gyp ERR! System Linux 4.14.71-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/opt/iobroker/node_modules/node-aead-crypto/build/Release/node-v57-linux-arm/node_aead_crypto.node" "--module_name=node_aead_crypto" "--module_path=/opt/iobroker/node_modules/node-aead-crypto/build/Release/node-v57-linux-arm" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v57"
gyp ERR! cwd /opt/iobroker/node_modules/node-aead-crypto
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/iobroker/node_modules/node-aead-crypto/build/Release/node-v57-linux-arm/node_aead_crypto.node --module_name=node_aead_crypto --module_path=/opt/iobroker/node_modules/node-aead-crypto/build/Release/node-v57-linux-arm --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/iobroker/node_modules/node-aead-crypto/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.14.71-v7+
node-pre-gyp ERR! command "/usr/bin/node" "/opt/iobroker/node_modules/node-aead-crypto/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /opt/iobroker/node_modules/node-aead-crypto
node-pre-gyp ERR! node -v v8.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-aead-crypto@2.0.0 install:default: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-aead-crypto@2.0.0 install:default script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
child_process.js:645
    throw err;
    ^

Error: Command failed: npm run install:default
    at checkExecSyncError (child_process.js:602:13)
    at execSync (child_process.js:642:13)
    at Object.<anonymous> (/opt/iobroker/node_modules/node-aead-crypto/lib/install.js:29:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-aead-crypto@2.0.0 (node_modules/node-aead-crypto):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-aead-crypto@2.0.0 install: `node lib/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

Thanks and regards,

Ralf

**Comment by gaudes** [comment]
Seems to be working. ioBroker reports Tradfri adapter as version 2.0.0.

Can you give me a hint how to install 1.5.3 ?

Regards, Ralf

**Comment by AlCalzone** [comment]
`npm i iobroker.tradfri@1.5.3`

**Comment by gaudes** [comment]
Hi,

thanks, I've just installed 1.5.3. I also recreated the instance, but still same problem with decimal places:

![image](https://user-images.githubusercontent.com/34286177/48304919-7aff4a80-e522-11e8-8112-e59ba23c4c91.png)


Thanks, Ralf

**Comment by AlCalzone** [comment]
Ich konnte das Problem nachvollziehen. Lag an einer fehlerhaften Behandlung des Wertes in den Einstellungen (Zeichenkette statt Zahl). Sollte mit v1.5.4 behoben sein.

**Comment by gaudes** [comment]
Hi,

works perfect. Thank you.

Regards, Ralf
